name: publish

on:
  push:
    branches:
      - main

env:
  GAR: asia-northeast1-docker.pkg.dev
  GCR: gcr.io

jobs:
  artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: 'stable'
          cache: true 
      - name: Build go module
        run: |
          GOARCH="amd64" GOOS="linux" go build -o ./.artifacts/helloworld ./cmd/helloworld/main.go
      - name: Log in to GCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.GCR }}
          username: _json_key
          password: ${{ secrets.GCP_SA }}
      - name: Login to GAR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.GAR }}
          username: _json_key
          password: ${{ secrets.GCP_SA }}
      - name: Build and push helloworld image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            ${{ env.GCR }}/knanao/helloworld:latest
            ${{ env.GAR }}/knanao/helloworld:latest
