name: publish

on:
  push:
    branches:
      - main

env:
  GAR: asia-northeast1-docker.pkg.dev
  GCR: gcr.io

jobs:
  artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: 'stable'
      - name: Build go module
        run: |
          GOARCH=$(go version | cut -d ' ' -f4 | cut -d/ -f2) GOOS=$(go version | cut -d ' ' -f4 | cut -d/ -f1) go build -o ./.artifacts/helloworld ./cmd/helloworld/main.go
      - name: Log in to GCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.GCR }}
          username: _json_key
          password: ${{ secrets.GCP_SA }}
      - name: Login to GAR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.GAR }}
          username: _json_key
          password: ${{ secrets.GCP_SA }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push helloworld image
        uses: docker/build-push-action@v4
        with:
          push: true
          provenance: true
          platforms: linux/amd64,linux/arm64
          context: .
          file: cmd/helloworld/Dockerfile
          tags: |
            ${{ env.GCR }}/knanao/helloworld:latest
            ${{ env.GAR }}/knanao/helloworld/helloworld:latest
